# Site Settings
lang: en
title: myLabPCB
tagline: The house of The myCPU Project
email: mylabpcb@gmail.com
description: >
  The house of the myCPU Project and myEnigma
baseurl: ""
url: "https://mycpu.mylabpcb.com"
permalink: pretty
favicon: /img/logo_icon.png
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
remote-theme: bulma-clean-theme
paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: mylabpcb


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: G-BFTJ7WDJ3N


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      hide_footer: true
      hide_hero: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: ""
      layout: post
      image: 
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: 
    show_sidebar: false
